server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: surveillance
          uri: lb://surveillance-ms
          predicates:
            - Path=/api/surveillance/**
          filters:
            - StripPrefix=1
        - id: maintenance
          uri: lb://maintenance-ms
          predicates:
            - Path=/api/maintenance/**
          filters:
            - StripPrefix=2
  config:
    import: optional:configserver:http://config-server:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
