# Configuration DEV pour maintenance

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/maintenance_db_dev
  jpa:
    show-sql: true  # On veut voir les requêtes en dev
    hibernate:
      ddl-auto: create-drop  # Recrée la base à chaque démarrage (dev uniquement !)

logging:
  level:
    com.imen.microservices.maintenance: DEBUG  # Logs détaillés en dev
    org.hibernate: DEBUG