spring:
  datasource:
    url: jdbc:postgresql://surveillance-db:5432/surveillance
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9092
    topic:
      anomalies: anomalies.new
  config:
    import: optional:configserver:http://config-server:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
